version: "3.5"
services:
  hadoop-cluster:
    image: kycloud/hadoop:1.0.0
    container_name: hadoop
    hostname: hadoop-master
    expose: ["9000"]
    ports: ["50070"]

  hbase-cluster:
    image: kycloud/hbase:1.0.0
    container_name: hbase
    hostname: hbase-master
    ports: ["16010"]
